#!/bin/sh

# This should be a shell script that copies
# a remote backup of the Subversion repository
# to a local directory.
# From the remote backup directory, it picks
# the latest created backup.
#
# To run periodically from a scheduler like
# cron, for example:
#
#   $ crontab -l
#   # Copy latest remote SVN backup every day
#   30 03 * * * /home/martijn/bin/copy_svn_backup >> /var/log/copy_svn_backup 2>&1
#
# Martijn Vermaat, 2005-05-10


# Configuration

REMOTE_HOST=christina
REMOTE_DIR=/var/backups/subversion
LOCAL_DIR=/backup/christina/subversion/automated


# Start of script

echo `date`


# Get filename for latest backup

echo "Checking for latest backup file..."

LATEST=`ssh $REMOTE_HOST "ls $REMOTE_DIR | tail -1"`

echo "Latest backup: $LATEST"


# Check if this backup is not already present

if [ -f "$LOCAL_DIR/$LATEST" ]; then

    # This backup is already present

    echo "Backup already present locally"

else

    # Copy latest backup to local dir

    echo "Copying $LATEST from $REMOTE_HOST:$REMOTE_DIR to $LOCAL_DIR"

    scp $REMOTE_HOST:$REMOTE_DIR/$LATEST $LOCAL_DIR

    echo "Done"

fi


# Extra newline

echo
